{{- if eq .Values.provider "cloudflare" }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "external-dns.name" . }}-cloudflare-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    name: {{ .Values.cloudflare.secret.store.name }}
    kind: {{ .Values.cloudflare.secret.store.kind }}
  target:
    creationPolicy: 'Owner'
  data:
    - secretKey: cf-api-token
      remoteRef:
        key: {{ required "param cloudflare.secret.key is required for generating cloudflare-secret" .key }}
        property: {{ .property }}
  {{- end }}
