{{- if eq .Values.provider "pdns" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "external-dns.name" . }}-pdns-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
spec:
  {{- with .Values.pdns.apiKeySecret }}
  secretStoreRef:
    name: {{ .store.name }}
    kind: {{ .store.kind }}
  target:
    creationPolicy: 'Owner'
  data:
    - secretKey: api-key
      remoteRef:
        key: {{ required "param pdns.apiKeySecret.key is required for generating pdns-secret" .key }}
        property: {{ .property }}
  {{- end }}
{{- end }}
